apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-creds-refresh
  namespace: acme-system
spec:
  schedule: 0 */11 * * *
  # schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ecr-creds-refresh
              image: papihack/k8s-aws-toolkit:sasuke
              command:
                # - /bin/bash
                # - '-c'
                - '/usr/local/scripts/SECRETS_UPDATE_SCRIPT.sh'
              env:
                - name: AWS_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: aws-creds-config
                      key: AWS_REGION
                - name: SECRET_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: aws-creds-config
                      key: IMG_PULL_SECRET_NAME
                - name: AWS_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_ACCOUNT_ID
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_SECRET_ACCESS_KEY
              volumeMounts:
              - name: secrets-update-script
                mountPath: "/usr/local/scripts"
                readOnly: false
              imagePullPolicy: IfNotPresent
          volumes:
            - name: secrets-update-script
              configMap:
                name: aws-creds-config
                defaultMode: 0777
          restartPolicy: OnFailure
          serviceAccountName: aws-creds-cronjob-sa
          serviceAccount: aws-creds-cronjob-sa
