apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-creds-cronjob-role
  namespace: acme-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-creds-cronjob-rolebinding
  namespace: acme-system
subjects:
- kind: ServiceAccount
  name: aws-creds-cronjob-sa
  namespace: acme-system
roleRef:
  kind: Role
  name: aws-creds-cronjob-role
  apiGroup: rbac.authorization.k8s.io
